version: '3'
services:
  gnb:
    image: gradiant/srsran-5g:23_10_1
    command: 
      - gnb 
    privileged: true
    cap_add:
      - all
    environment:
      GNB_HOSTNAME: gnb
      UE_HOSTNAME: ue
      AMF_HOSTNAME: amf
      AMF_BIND_INTERFACE: eth0
      DEVICE_DRIVER: zmq   
      DEVICE_ARGS: default
      SRATE: 23.04   
      TX_GAIN: 75  
      RX_GAIN: 75
      DL_ARFCN: 368500
      BAND: 3   
      BANDWIDTH: 20
      SCS: 15   
      PLMN: 99970
      TAC: 1   
      OTW_FORMAT: default
     
  ue:
    image: gradiant/srsran-4g:23_11
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: gnb
      UE_HOSTNAME: ue
      DL_EARFCN: 2850
      BANDS: 3
      APN: internet
      APN_PROTOCOL: ipv4
      SRATE: 23.04
      TX_GAIN: 50
      RX_GAIN: 40
      OPC: E8ED289DEBA952E4283B54E88E6183CA
      KEY: 465B5CE8B199B49FAA5F0A2EE238A6BC
      MCC: 999
      MNC: 70
      MSISDN: "0000000001"
      EUTRA_NOF_CARRIERS: 0
      NR_NOF_CARRIERS: 1
      NR_MAX_NOF_PRB: 106 
      NR_NOF_PRB: 106
      SRSUE_5G: true
      ZMQ: true

      