version: '3'
services:
  ue:
    image: openverso/srsran-4g:23_11
    volumes:
      - ./srsUE.conf:/etc/srsran/ue.conf
    command: 
      - ue
    privileged: true
    cap_add:
      - all
    environment:
      ENB_HOSTNAME: gnb
      UE_HOSTNAME: ue