version: '3'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  webui:
    image: openverso/open5gs-webui:2.7.0  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
      NODE_ENV: dev
    ports:
      - 9999:9999
  smf:
    image: openverso/open5gs:2.7.0
    command: open5gs-smfd    
    restart : on-failure 
  mme:
    image: openverso/open5gs:2.7.0
    command: open5gs-mmed
    restart: on-failure
    ports:
      - 36412:36412
  sgwc:
    image: openverso/open5gs:2.7.0
    command: open5gs-sgwcd
    restart : on-failure
  sgwu:
    image: openverso/open5gs:2.7.0
    command: open5gs-sgwud
    restart : on-failure
  upf:
    image: openverso/open5gs:2.7.0
    command: ["open5gs-upfd"]
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
  pcrf:
    image: openverso/open5gs:2.7.0
    command: ["open5gs-pcrfd"]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  hss:
    image: openverso/open5gs:2.7.0
    command: open5gs-hssd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  nrf:
    image: openverso/open5gs:2.4.4
    command: open5gs-nrfd   
    restart : on-failure 

