version: '3'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: open5gs
  amf:
    image: gradiant/open5gs:2.3.2
    command: 
      - open5gs-amfd 
    restart : on-failure
    
  ausf:
    image: gradiant/open5gs:2.3.2
    command: 
      - open5gs-ausfd
    restart : on-failure
    
  bsf:
    image: gradiant/open5gs:2.3.2
    command: 
      - open5gs-bsfd
    restart : on-failure
  
  hss:
    image: gradiant/open5gs:2.3.2
    command: open5gs-hssd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure

  nrf:
    image: gradiant/open5gs:2.3.2
    command: open5gs-nrfd
    restart : on-failure 
    
  nssf:
    image: gradiant/open5gs:2.3.2
    command: open5gs-nssfd   
    restart : on-failure 
    
  pcf:
    image: gradiant/open5gs:2.3.2
    command: 
      - open5gs-pcfd
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart : on-failure
    
  pcrf:
    image: gradiant/open5gs:2.3.2
    command: ["open5gs-pcrfd"]
    environment:
      DB_URI: mongodb://mongo/open5gs
    restart: on-failure
  mme:
    image: gradiant/open5gs:2.3.2
    command: open5gs-mmed
    restart: on-failure
  sgwc:
    image: gradiant/open5gs:2.3.2
    command: open5gs-sgwcd
    restart : on-failure
  sgwu:
    image: gradiant/open5gs:2.3.2
    command: open5gs-sgwud
    restart : on-failure
  smf:
    image: gradiant/open5gs:2.3.2
    command: open5gs-smfd    
    restart : on-failure 
    
  udm:
    image: gradiant/open5gs:2.3.2
    restart: on-failure
    command: 
      - open5gs-udmd
    
  udr:
    image: gradiant/open5gs:2.3.2
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    command: 
      - open5gs-udrd
    
  upf:
    image: gradiant/open5gs:2.3.2
    command:
      - open5gs-upfd
    cap_add:
      - all
    privileged: true
    restart: on-failure
    ports:
      - 2152:2152
    
  webui:
    image: gradiant/open5gs-webui:2.3.2  
    restart: on-failure
    environment:
      DB_URI: mongodb://mongo/open5gs
    ports:
      - 3000:3000
    
  # portainer:
  #   image: portainer/portainer-ce
  #   ports:
  #   - 9000:9000
  #   volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
