sbi:
    server:
      no_tls: true
    client:
      no_tls: true

bsf:
  sbi:
    - dev: eth0
      advertise: bsf
# scp:
#     sbi:
#       - name: scp
nrf:
  sbi:
    - name: nrf
parameter:
max:
time: