db_uri: mongodb://localhost/open5gs
logger:
  file: /opt/open5gs/var/log/open5gs/hss.log
  # level: info   # fatal|error|warn|info(default)|debug|trace

global:
# max:
#   ue: 1024 # The number of UE can be increased depending on memory size.
#    peer: 64

hss:
  freeDiameter: /opt/open5gs/etc/freeDiameter/hss.conf
#  sms_over_ims: "sip:smsc.mnc001.mcc001.3gppnetwork.org:7060;transport=tcp"
#  use_mongodb_change_stream: true
