### For reference, see `/opt/open5gs/etc/orig/open5gs/`
sbi:
    server:
      no_tls: true
    client:
      no_tls: true

nrf:
  sbi:
    - dev: eth0
      advertise: nrf
# scp:
#     sbi:
#       - name: scp
parameter:
max:
time: