### For reference, see `/opt/open5gs/etc/orig/open5gs/`
pcf:
  sbi:
    - dev: eth0
      advertise: pcf
  metrics:
    - addr: 0.0.0.0
      port: 9090
# scp:
#     sbi:
#       - name: scp
nrf:
  sbi:
    - name: nrf
parameter:
max:
time: