### For reference, see `/opt/open5gs/etc/orig/open5gs/`
smf:
  sbi:
    - dev: eth0
      advertise: smf
  gtpc:
  gtpu:
  pfcp:
  metrics:
    - addr: 0.0.0.0
      port: 9090
  subnet:
    - addr: 10.45.0.1/16
    #- addr: cafe::1/64

  dns:
    - 8.8.8.8
    - 8.8.4.4
    #- 2001:4860:4860::8888
    #- 2001:4860:4860::8844
  mtu: 1400
  ctf:
    enabled: auto
  freeDiameter: smf.conf
# scp:
#     sbi:
#       - name: scp
nrf:
  sbi:
    - name: nrf
upf:
  pfcp:
    - name: upf

parameter:
max:
time: