
### For reference, see `/opt/open5gs/etc/orig/open5gs/`
sbi:
    server:
      no_tls: true
    client:
      no_tls: true

udm:
  sbi:
    - dev: eth0
      advertise: udm
# scp:
#     sbi:
#       - name: scp
nrf:
  sbi:
    - name: nrf
parameter:
max:
time: