### For reference, see `/opt/open5gs/etc/orig/open5gs/`
sbi:
    server:
      no_tls: true
    client:
      no_tls: true

udr:
  sbi:
    - dev: eth0
      advertise: udr
# scp:
#     sbi:
#       - name: scp
nrf:
  sbi:
    - name: nrf
parameter:
max:
time: