ARG version=1.2.2

FROM openverso/oai-enb:${version}

# with images
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
		uhd-host && \
    rm -rf /var/lib/apt/lists/*

RUN uhd_images_downloader
