version: '2.4'
services: 
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: free5gc
  nrf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/nrfcfg.yaml:/etc/free5gc/nrfcfg.yaml
    command: ["nrf","-nrfcfg","/etc/free5gc/nrfcfg.yaml"]
    restart : on-failure
  udr:
    image: openverso/free5gc:3.0.5
    command: ["udr","-udrcfg","/etc/free5gc/udrcfg.yaml"]
    restart : on-failure
  amf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/amfcfg.yaml:/etc/free5gc/amfcfg.yaml
    command: ["amf","-amfcfg","/etc/free5gc/amfcfg.yaml"]
    restart : on-failure
  smf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/smfcfg.yaml:/etc/free5gc/smfcfg.yaml
      - ./configs/free5gc/uerouting.yaml:/etc/free5gc/uerouting.yaml
    command: 
      - "smf"
      - "--smfcfg=/etc/free5gc/smfcfg.yaml"
      - "--uerouting=/etc/free5gc/uerouting.yaml"
    restart : on-failure
  pcf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/pcfcfg.yaml:/etc/free5gc/pcfcfg.yaml
    command: ["pcf","-pcfcfg","/etc/free5gc/pcfcfg.yaml"]
    restart : on-failure
  udm:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/udmcfg.yaml:/etc/free5gc/udmcfg.yaml
    command: ["udm","-udmcfg","/etc/free5gc/udmcfg.yaml"]
    restart : on-failure
  nssf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/nssfcfg.yaml:/etc/free5gc/nssfcfg.yaml
    command: ["nssf","-nssfcfg","/etc/free5gc/nssfcfg.yaml"]
    restart : on-failure
  ausf:
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/ausfcfg.yaml:/etc/free5gc/ausfcfg.yaml
    command: ["ausf","-ausfcfg","/etc/free5gc/ausfcfg.yaml"]
    restart : on-failure
  upf:
    cap_add:
      - NET_ADMIN
    image: openverso/free5gc:3.0.5
    volumes:
      - ./configs/free5gc/upfcfg.yaml:/etc/free5gc/upfcfg.yaml
    command: ["upf","-f","/etc/free5gc/upfcfg.yaml"]
    restart : on-failure

  webconsole:
    image: openverso/free5gc-webconsole:1.0.1
    restart: on-failure
    ports:
      - 5000:5000
    volumes:
      - ./configs/free5gc/webuicfg.yaml:/etc/free5gc/webuicfg.yaml

  portainer:
    image: portainer/portainer-ce
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
