#
# logger:
#
#  o Set OGS_LOG_INFO to all domain level
#   - If `level` is omitted, the default level is OGS_LOG_INFO)
#   - If `domain` is omitted, the all domain level is set from 'level'
#    (Nothing is needed)
#
#  o Set OGS_LOG_ERROR to all domain level
#   - `level` can be set with none, fatal, error, warn, info, debug, trace
#    level: error
#
#  o Set OGS_LOG_DEBUG to mme/emm domain level
#    level: debug
#    domain: mme,emm
#
#  o Set OGS_LOG_TRACE to all domain level
#    level: trace
#    domain: core,pfcp,gtp,sgwu,event,tlv,mem,sock
#
logger:
    file: /opt/open5gs/var/log/open5gs/sgwu.log

#
# sgwu:
#
#  <PFCP Server>
#
#  o PFCP Server(127.0.0.6:8805, ::1:8805)
#    pfcp:
#      - addr: 127.0.0.6
#      - addr: ::1
#
#  o PFCP-U Server(127.0.0.1:2152, [::1]:2152)
#    pfcp:
#      - name: localhost
#
#  o PFCP Option (Default)
#    - so_bindtodevice : NULL
#
#    pfcp:
#      addr: 127.0.0.6
#      option:
#        so_bindtodevice: vrf-blue
#
#  <GTP-U Server>
#
#  o GTP-U Server(127.0.0.6:2152, [::1]:2152)
#    gtpu:
#      - addr: 127.0.0.6
#      - addr: ::1
#
#  o GTP-U Server(127.0.0.1:2152, [::1]:2152)
#    gtpu:
#      - name: localhost
#
#  o User Plane IP Resource information
#    gtpu:
#      - addr:
#        - 127.0.0.6
#        - ::1
#        teid_range_indication: 4
#        teid_range: 10
#        network_instance: internet
#        source_interface: 0
#      - addr: 127.0.10.4
#        teid_range_indication: 4
#        teid_range: 5
#        network_instance: ims
#        source_interface: 1
#
#  o Provide custom SGW-U GTP-U address to be advertised inside S1AP messages
#    gtpu:
#      - addr: 10.4.128.21
#        advertise: 172.24.15.30
#
#    gtpu:
#      - addr: 10.4.128.21
#        advertise:
#        - 127.0.0.1
#        - ::1
#
#    gtpu:
#      - addr: 10.4.128.21
#        advertise: sgw1.epc.mnc001.mcc001.3gppnetwork.org
#
#    gtpu:
#      - dev: ens3
#        advertise: sgw1.epc.mnc001.mcc001.3gppnetwork.org
#
#  o GTP-U Option (Default)
#    - so_bindtodevice : NULL
#
#    gtpu:
#      addr: 127.0.0.6
#      option:
#        so_bindtodevice: vrf-blue
#
sgwu:
    pfcp:
      - addr: 127.0.0.6
    gtpu:
      - addr: 127.0.0.6

#
# sgwc:
#
#  <PFCP Client>>
#
#  o PFCP Client(127.0.0.3:8805)
#
#    pfcp:
#      addr: 127.0.0.3
#
sgwc:

#
# parameter:
#
#  o Disable use of IPv4 addresses (only IPv6)
#      no_ipv4: true
#
#  o Disable use of IPv6 addresses (only IPv4)
#      no_ipv6: true
#
#  o Prefer IPv4 instead of IPv6 for estabishing new GTP connections.
#      prefer_ipv4: true
#
parameter:

#
# max:
#
# o Maximum Number of UE per AMF/MME
#    ue: 1024
# o Maximum Number of gNB/eNB per AMF/MME
#    gnb: 64
#
max:

#
# time:
#
#  o Message Wait Duration (Default : 10,000 ms = 10 seconds)
#
#  o Message Wait Duration (3000 ms)
#    message:
#        duration: 3000
time:
