#
#  o Set OGS_LOG_INFO to all domain level
#   - If `level` is omitted, the default level is OGS_LOG_INFO)
#   - If `domain` is omitted, the all domain level is set from 'level'
#    (Default values are used, so no configuration is required)
#
#  o Set OGS_LOG_ERROR to all domain level
#   - `level` can be set with none, fatal, error, warn, info, debug, trace
#  logger:
#    level: error
#
#  o Set OGS_LOG_DEBUG to mme/emm domain level
#  logger:
#    level: debug
#    domain: mme,emm
#
#  o Set OGS_LOG_TRACE to all domain level
#  logger:
#    level: trace
#    domain: core,sbi,ausf,event,tlv,mem,sock
#
logger:
    file: @localstatedir@/log/open5gs/upf.log

#
#  <PFCP Server>
#
#  o PFCP Server(127.0.0.7:8805, ::1:8805)
#  upf:
#    pfcp:
#      - addr: 127.0.0.7
#      - addr: ::1
#
#  o PFCP-U Server(127.0.0.1:2152, [::1]:2152)
#  upf:
#    pfcp:
#      name: localhost
#
#  o PFCP Option (Default)
#    - so_bindtodevice : NULL
#
#  upf:
#    pfcp:
#      addr: 127.0.0.7
#      option:
#        so_bindtodevice: vrf-blue
#
#  o Provide custom PFCP address to be advertised to SMF in PFCP association
#      request/respond
#  upf:
#    pfcp:
#      - addr: 0.0.0.0
#        advertise: open5gs-smf.svc.local
#
#  <GTP-U Server>>
#
#  o GTP-U Server(127.0.0.7:2152, [::1]:2152)
#  upf:
#    gtpu:
#      - addr: 127.0.0.7
#      - addr: ::1
#
#  o GTP-U Server(127.0.0.1:2152, [::1]:2152)
#  upf:
#    gtpu:
#      name: localhost
#
#  o User Plane IP Resource information
#  upf:
#    gtpu:
#      - addr:
#        - 127.0.0.7
#        - ::1
#        teid_range_indication: 4
#        teid_range: 10
#        network_instance: internet
#        source_interface: 0
#      - addr: 127.0.10.4
#        teid_range_indication: 4
#        teid_range: 5
#        network_instance: ims
#        source_interface: 1
#
#  o Provide custom UPF GTP-U address to be advertised inside NGAP messages
#  upf:
#    gtpu:
#      - addr: 10.4.128.21
#        advertise: 172.24.15.30
#
#  upf:
#    gtpu:
#      - addr: 10.4.128.21
#        advertise:
#        - 127.0.0.1
#        - ::1
#
#  upf:
#    gtpu:
#      - addr: 10.4.128.21
#        advertise: upf1.5gc.mnc001.mcc001.3gppnetwork.org
#
#  upf:
#    gtpu:
#      - dev: ens3
#        advertise: upf1.5gc.mnc001.mcc001.3gppnetwork.org
#
#  o GTP-U Option (Default)
#    - so_bindtodevice : NULL
#
#  upf:
#    gtpu:
#      addr: 127.0.0.7
#      option:
#        so_bindtodevice: vrf-blue
#
#  <Subnet for UE network>
#
#  Note that you need to setup your UE network using TUN device.
#  (ogstun, ogstun2, ogstunX, ..)
#
#  o IPv4 Pool
#    $ sudo ip addr add 10.45.0.1/16 dev ogstun
#
#  upf:
#    subnet:
#      addr: 10.45.0.1/16
#
#  o IPv4/IPv6 Pool
#    $ sudo ip addr add 10.45.0.1/16 dev ogstun
#    $ sudo ip addr add 2001:db8:cafe::1/48 dev ogstun
#
#  upf:
#    subnet:
#      - addr: 10.45.0.1/16
#      - addr: 2001:db8:cafe::1/48
#
#
#  o Specific DNN/APN(e.g 'ims') uses 10.46.0.1/16, 2001:db8:babe::1/48
#    All other APNs use 10.45.0.1/16, 2001:db8:cafe::1/48
#    $ sudo ip addr add 10.45.0.1/16 dev ogstun
#    $ sudo ip addr add 10.46.0.1/16 dev ogstun
#    $ sudo ip addr add 2001:db8:cafe::1/48 dev ogstun
#    $ sudo ip addr add 2001:db8:babe::1/48 dev ogstun
#
#    ; If the UE has unknown DNN/APN(not internet/ims), SMF/UPF will crash.
#
#  upf:
#    subnet:
#      - addr: 10.45.0.1/16
#        dnn: internet
#      - addr: 2001:db8:cafe::1/48
#        dnn: internet
#      - addr: 10.46.0.1/16
#        dnn: ims
#      - addr: 2001:db8:babe::1/48
#        dnn: ims
#
#  o Specific DNN/APN with the FALLBACK SUBNET(10.47.0.1/16)
#    ; Note that put the FALLBACK SUBNET last to avoid SMF/UPF crash.
#
#  upf:
#    subnet:
#      - addr: 10.45.0.1/16
#        dnn: internet
#      - addr: 10.46.0.1/16
#        dnn: ims
#      - addr: 10.50.0.1/16 ## FALLBACK SUBNET
#
#  o Multiple Devices (default: ogstun)
#    $ sudo ip addr add 10.45.0.1/16 dev ogstun
#    $ sudo ip addr add 2001:db8:cafe::1/48 dev ogstun2
#    $ sudo ip addr add 10.46.0.1/16 dev ogstun3
#    $ sudo ip addr add 2001:db8:babe::1/48 dev ogstun3
#
#  upf:
#    subnet:
#      - addr: 10.45.0.1/16
#        dnn: internet
#      - addr: 2001:db8:cafe::1/48
#        dnn: internet
#        dev: ogstun2
#      - addr: 10.46.0.1/16
#        dnn: ims
#        dev: ogstun3
#      - addr: 2001:db8:babe::1/48
#        dnn: ims
#        dev: ogstun3
#
#  <Metrics Server>
#
#  o Metrics Server(http://<any address>:9090)
#  upf:
#    metrics:
#    - addr: 0.0.0.0
#      port: 9090
#
upf:
    pfcp:
      - addr: 127.0.0.7
    gtpu:
      - addr: 127.0.0.7
    subnet:
      - addr: 10.45.0.1/16
      - addr: 2001:db8:cafe::1/48
    metrics:
      - addr: 127.0.0.7
        port: 9090

#
#  <PFCP Client>>
#
#  o PFCP Client(127.0.0.4:8805)
#  smf:
#    pfcp:
#      addr: 127.0.0.4
#
smf:

#
#  o Number of output streams per SCTP associations.
#  parameter:
#    sctp_streams: 30
#
#  o Disable use of IPv4 addresses (only IPv6)
#  parameter:
#    no_ipv4: true
#
#  o Disable use of IPv6 addresses (only IPv4)
#  parameter:
#    no_ipv6: true
#
#  o Prefer IPv4 instead of IPv6 for estabishing new GTP connections.
#  parameter:
#    prefer_ipv4: true
#
parameter:

#
# o Maximum Number of UE
# max:
#   ue: 1024
#
# o Maximum Number of Peer(S1AP/NGAP, DIAMETER, GTP, PFCP or SBI)
# max:
#   peer: 64
#
max:

#
#  o Message Wait Duration (Default : 10,000 ms = 10 seconds)
#    (Default values are used, so no configuration is required)
#
#  o Message Wait Duration (3000 ms)
#  time:
#    message:
#        duration: 3000
time:
