version: '3'
services: 
  enodeb:
    image: openverso/oai-enb:1.2.2
    privileged: true
    volumes:
      - ./oai-config/band7.tm1.25PRB.b210.conf:/opt/oai/etc/band7.tm1.25PRB.b210.conf 
      - /dev/bus/usb:/dev/bus/usb
      - ./uhd_images:/usr/share/uhd/images
    cap_add:
      - all
    environment:
      ENB_TEMPLATE_PATH: /opt/oai/etc/band7.tm1.25PRB.b210.conf 
      MME_HOSTNAME: mme
      MCC: "901"
      MNC: "70"
      TAC: "1"