FROM registry.redhat.io/ubi9:latest as builder

ARG version=2.6.4
ENV VERSION=$version

LABEL org.opencontainers.image.authors="Alaitz Mendiola <alaitz@redhat.com>" \
      org.opencontainers.image.vendor="Red Hat Inc." \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="$version"

RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
        && rpm -ql epel-release     

RUN dnf install -y \
        python3 \
        python3-pip \
        python3-wheel \
        git \
        cmake \
        gcc \
        gcc-c++ \
        libgcrypt-devel \
        openssl-devel \
        libidn-devel \
        cyrus-sasl-devel \
        libbson-devel \
        libyaml-devel \
        libnghttp2-devel \
        libcurl-devel \
        libtins-devel \
        wget \
        iproute \
        net-tools \
        iputils \
        bind-utils \
        gettext \
        iptables \
        libtalloc \
        libtalloc.so.2 \
        && dnf clean all

RUN pip3 install ninja && pip install meson

RUN dnf localinstall -y \
    https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/libtalloc-devel-2.3.4-1.el9.x86_64.rpm\
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libmicrohttpd-0.9.72-4.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/gnutls-3.7.6-20.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/gnutls-c++-3.7.6-20.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/gnutls-dane-3.7.6-20.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/nettle-3.8-3.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/gmp-6.2.0-11.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/gmp-c++-6.2.0-11.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/gmp-devel-6.2.0-11.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/nettle-devel-3.8-3.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/libtasn1-4.16.0-8.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libtasn1-tools-4.16.0-8.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libtasn1-devel-4.16.0-8.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libidn2-devel-2.3.0-7.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/p11-kit-devel-0.24.1-2.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/gnutls-devel-3.7.6-20.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/libmicrohttpd-devel-0.9.72-4.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/lksctp-tools-devel-1.0.19-2.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libzstd-devel-1.5.1-2.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/snappy-1.1.8-8.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/m/mongo-c-driver-libs-1.23.5-1.el9.x86_64.rpm\
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/flex-2.6.4-9.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/m/mongo-c-driver-devel-1.23.5-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/bison-3.7.4-5.el9.x86_64.rpm

RUN	mkdir -p /opt/open5gs && \
      cd /tmp && \
      git clone https://github.com/open5gs/open5gs && \
	cd open5gs && \
      if [ "$VERSION" = "dev" ]; then \
            git checkout main; \
            wget https://api.github.com/repos/open5gs/open5gs/git/refs/heads/main -O /open5gs-ver.json; \
      else \
            git checkout v$VERSION; \
            wget https://api.github.com/repos/open5gs/open5gs/git/refs/tags/v$VERSION -O /open5gs-ver.json; \
      fi && \
      meson build --prefix=/opt/open5gs && \
      ln -s /opt/open5gs/subprojects/ /opt/open5gs/../subprojects && \
      ninja -C build install

CMD ["/bin/bash"]

FROM registry.redhat.io/ubi9-minimal:latest

ARG version=2.6.1
ENV VERSION=$version

LABEL org.opencontainers.image.authors="Alaitz Mendiola <alaitz@redhat.com>" \
      org.opencontainers.image.vendor="Red Hat Inc." \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.version="$version"
        
RUN microdnf install -y \
    info \
    lksctp-tools \
    iproute \
    iputils \
    procps-ng \
    net-tools \
    git \
    make \        
    pkgconf \
    pkgconf-m4 \
    libtalloc \
    libtalloc.so.2  \
    iptables && microdnf clean all

RUN rpm -ivh \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/pkgconf-pkg-config-1.7.3-10.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/CRB/x86_64/os/Packages/libtalloc-devel-2.3.4-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/libmicrohttpd-0.9.72-4.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/l/libbson-1.23.5-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/l/libmongocrypt-1.8.1-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/snappy-1.1.8-8.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/libicu-67.1-9.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/m/mongo-c-driver-libs-1.23.5-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/m/mongo-c-driver-1.23.5-1.el9.x86_64.rpm \
    https://rpmfind.net/linux/epel/9/Everything/x86_64/Packages/l/libidn-1.38-4.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/iperf3-3.9-9.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/AppStream/x86_64/os/Packages/tcpdump-4.99.0-6.el9.x86_64.rpm \
    https://rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/os/Packages/traceroute-2.1.0-16.el9.x86_64.rpm

RUN git clone https://github.com/magnific0/wondershaper && \
    cd wondershaper && \
    make install

ENV APP_ROOT=/opt/open5gs
COPY --from=builder /opt/open5gs/bin ${APP_ROOT}/bin/
COPY --from=builder /opt/open5gs/etc ${APP_ROOT}/etc/orig
COPY configs/ ${APP_ROOT}/etc/
COPY --from=builder /opt/open5gs/lib64/ /usr/local/lib/

ENV PATH=${APP_ROOT}/bin:${PATH} HOME=${APP_ROOT}
WORKDIR ${APP_ROOT}

RUN echo /usr/local/lib > /etc/ld.so.conf.d/open5gs.conf
RUN ldconfig
COPY entrypoint.sh /entrypoint.sh

#Default CONF values
ENV DB_URI=mongodb://mongo/open5gs

ENV IPV4_TUN_SUBNET="10.45.0.0/16" \
    IPV4_TUN_ADDR="10.45.0.1/16" \
    IPV6_TUN_ADDR="cafe::1/64" \
    ENABLE_NAT=true

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]

