version: '3'
services: 
  gnb1:
    image: gradiant/ueransim:3.2.6
    container_name: gnb1
    command: 
      - gnb
    environment:
      AMF_HOSTNAME: amf
      GNB_HOSTNAME: gnb1
      TAC: '1'
      MCC: '999'
      MNC: '70'
      SST: '1'
      SD: '0xffffff'
  ues1:
    image: gradiant/ueransim:3.2.6
    command: ['ue','-n','3']
    cap_add:
      - all
    privileged: true
    environment:
      GNB_HOSTNAME: gnb1
      APN: internet
      MSISDN: '0000000001'
      MCC: '999'
      MNC: '70'
      KEY: '465B5CE8B199B49FAA5F0A2EE238A6BC'
      OP_TYPE: OPC
      OP: 'E8ED289DEBA952E4283B54E88E6183CA'
      SST: '1'
      SD: '0xffffff'
