upf:
    pfcp:
    gtpu:
    subnet:
      - addr: 192.168.100.1/24
        dev: ogstun
        dnn: internet
      - addr: 2001:230:cafe::1/48
        dev: ogstun
        dnn: internet
      - addr: 192.168.101.1/24
        dnn: ims
        dev: ogstun2
      - addr: 2001:230:babe::1/48
        dnn: ims
        dev: ogstun2

smf:
    pfcp:
      - name: smf
parameter:
max:
pool:
